# Generated by Django 4.2.6 on 2023-10-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(choices=[('QUESTION', 'question_major'), ('TALK', 'talk'), ('INTERN', 'intern_review'), ('EXTERNAL', 'external_activity'), ('SCHOOL', 'school_story')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('major', models.CharField(max_length=15, null=True)),
                ('major_category_name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField()),
                ('like', models.IntegerField(default=0)),
                ('keep', models.IntegerField(default=0)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=20)),
                ('major_name', models.CharField(max_length=15)),
                ('student_id', models.BigIntegerField()),
                ('home_id', models.CharField(max_length=15)),
                ('home_password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=15)),
                ('admission_date', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('user_status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive'), ('WARN', 'warn'), ('BLOCK', 'block')], max_length=10)),
                ('major_id', models.ForeignKey(db_column='major_id', on_delete=django.db.models.deletion.CASCADE, to='main.major')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_comment', models.BigIntegerField(db_column='parent_comment', default=models.BigAutoField(primary_key=True, serialize=False))),
                ('contents', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField()),
                ('like', models.IntegerField(default=0)),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
