# Generated by Django 4.2.6 on 2023-11-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_comment',
            old_name='post_date',
            new_name='comment_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Post_Like',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('delete_date', models.DateTimeField()),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post_bookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookmark_date', models.DateTimeField(auto_now_add=True)),
                ('delete_date', models.DateTimeField()),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
