# Generated by Django 4.2.6 on 2023-11-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_post_date_post_comment_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post_bookmark',
            name='delete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='delete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post_like',
            name='delete_date',
            field=models.DateTimeField(null=True),
        ),
    ]
