# Generated by Django 4.2.6 on 2023-11-04 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_board_comment_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_comment', models.BigIntegerField(db_column='parent_comment', default=models.BigAutoField(primary_key=True, serialize=False))),
                ('contents', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True)),
                ('like', models.IntegerField(default=0)),
                ('studypost_id', models.ForeignKey(db_column='studypost_id', on_delete=django.db.models.deletion.CASCADE, to='main.study')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
