# Generated by Django 4.2.6 on 2023-11-05 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_study_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Like',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('delete_date', models.DateTimeField(null=True)),
                ('studypost_id', models.ForeignKey(db_column='studypost_id', on_delete=django.db.models.deletion.CASCADE, to='main.study')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
