# Generated by Django 4.2.6 on 2023-11-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_study_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='main.board_comment'),
        ),
        migrations.AlterField(
            model_name='study_comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='main.study_comment'),
        ),
    ]
