# Generated by Django 4.2.6 on 2023-11-25 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_board_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usedbooktrade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='* 책 제목은 정확하게 기입해주세요.', max_length=100, verbose_name='상품명')),
                ('author', models.TextField(verbose_name='저자')),
                ('publisher', models.CharField(max_length=100, verbose_name='출판사')),
                ('price', models.TextField(verbose_name='판매가')),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to="'book_covers/'", verbose_name='상품 사진')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('is_written', models.BooleanField(verbose_name='필기 유무')),
                ('is_damaged', models.BooleanField(verbose_name='훼손 유무')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('delete_date', models.DateTimeField(null=True)),
                ('comment', models.IntegerField(default=0)),
                ('is_sold', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(db_column='seller', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Usedbooktrade_Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(null=True)),
                ('Usedbookpost_id', models.ForeignKey(db_column='usedbookpost_id', on_delete=django.db.models.deletion.CASCADE, to='main.usedbooktrade')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='main.usedbooktrade_comment')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
