# Generated by Django 4.2.6 on 2024-04-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usedbooktradedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedbooktrade',
            name='is_damaged',
        ),
        migrations.RemoveField(
            model_name='usedbooktrade',
            name='is_written',
        ),
        migrations.AddField(
            model_name='usedbooktrade',
            name='damage_level',
            field=models.CharField(choices=[('없음', '손상도 없음'), ('조금있음', '손상도 조금있음'), ('많음', '손상도 많음')], default='없음', max_length=20, verbose_name='손상도'),
        ),
    ]
