# Generated by Django 4.2.6 on 2024-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive'), ('WARN', 'warn'), ('BLOCK', 'block')], default='ACTIVE', max_length=10),
        ),
    ]
