# Generated by Django 4.2.6 on 2024-05-10 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_alter_user_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='auth_id',
            field=models.ForeignKey(db_column='auth_id', default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
