# Generated by Django 4.2.6 on 2024-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_token_auth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
