# Generated by Django 4.2.6 on 2024-05-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_token_access_alter_token_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_password_check',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
