# Generated by Django 4.2.6 on 2024-05-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_category_category_of_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to="'community/'", verbose_name='첨부 사진'),
        ),
    ]
