# Generated by Django 4.2.6 on 2024-05-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_board_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='community/', verbose_name='첨부 사진'),
        ),
        migrations.AlterField(
            model_name='usedbooktrade',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='상품 사진'),
        ),
    ]
