# Generated by Django 4.2.6 on 2024-05-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_board_imgfile_alter_usedbooktrade_imgfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbooktrade',
            name='origin_imgfile',
            field=models.CharField(max_length=150, null=True, verbose_name='상품 사진'),
        ),
        migrations.AlterField(
            model_name='usedbooktrade',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='판매자 상품 사진'),
        ),
    ]
