# Generated by Django 4.2.6 on 2024-05-18 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_usedbooktrade_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedbooktradedata',
            name='trade',
            field=models.ForeignKey(db_column='trade_id', on_delete=django.db.models.deletion.CASCADE, to='main.usedbooktrade'),
        ),
    ]
