# Generated by Django 4.2.6 on 2024-06-11 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_usedbooktradedata_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='keep',
            new_name='bookmark',
        ),
    ]
