# Generated by Django 4.2.6 on 2024-06-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_board_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
