# Generated by Django 4.2.6 on 2024-06-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_study_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
