# Generated by Django 4.2.6 on 2024-07-15 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_major_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='시작일')),
                ('end_date', models.DateTimeField(auto_now=True, verbose_name='종료일')),
                ('status', models.CharField(max_length=10, verbose_name='진행 상태')),
                ('mentee_id', models.ForeignKey(db_column='mentee_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='MentorRegistrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='멘토링 제목')),
                ('mentoring_category', models.CharField(choices=[('학습', '학습'), ('취업', '취업'), ('인간관계', '인간관계')], default='학습', max_length=20, verbose_name='멘토링 주제')),
                ('description', models.TextField(verbose_name='멘토링 설명')),
                ('place_type', models.CharField(choices=[('온라인', '온라인'), ('오프라인', '오프라인')], default='온라인', max_length=10, verbose_name='진행 방식')),
                ('period', models.TextField(verbose_name='멘토링 기간')),
                ('day', models.TextField(verbose_name='가능 요일')),
                ('mentee_num', models.IntegerField(verbose_name='모집 인원')),
                ('mentoring_keyword', models.TextField(verbose_name='멘토링 키워드')),
                ('mood_type', models.TextField(verbose_name='멘토링 분위기')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('delete_date', models.DateTimeField(null=True, verbose_name='삭제일')),
                ('admin_approval', models.BooleanField(default=False, verbose_name='관리자 승인 여부')),
                ('status', models.CharField(max_length=10, verbose_name='진행 상태')),
                ('applicants_num', models.IntegerField(default=0, verbose_name='신청 인원')),
                ('approval_num', models.IntegerField(default=0, verbose_name='승인 인원')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='멘토 이름')),
            ],
        ),
        migrations.CreateModel(
            name='MentoringReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(verbose_name='평점')),
                ('review_text', models.TextField(verbose_name='리뷰 내용')),
                ('recommend', models.BooleanField(default=False, verbose_name='추천 여부')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='리뷰 날짜')),
                ('mentoringdata_id', models.ForeignKey(db_column='mentoringdata_id', on_delete=django.db.models.deletion.CASCADE, to='main.mentoringdata')),
            ],
        ),
        migrations.AddField(
            model_name='mentoringdata',
            name='mentoring_id',
            field=models.ForeignKey(db_column='trade_id', on_delete=django.db.models.deletion.CASCADE, to='main.mentorregistrations'),
        ),
        migrations.CreateModel(
            name='MenteeApplications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='지원 동기')),
                ('add_text', models.TextField(verbose_name='멘토에게 하고 싶은 말')),
                ('day', models.TextField(verbose_name='가능 요일')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('mentor_approval', models.BooleanField(default=False, verbose_name='멘토 승인 여부')),
                ('mentoring_id', models.ForeignKey(db_column='mentoring_id', on_delete=django.db.models.deletion.CASCADE, to='main.mentorregistrations')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='멘티 이름')),
            ],
        ),
    ]
