# Generated by Django 4.2.6 on 2024-07-15 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_mentoringdata_mentorregistrations_mentoringreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeapplications',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='멘티 이름'),
        ),
        migrations.AlterField(
            model_name='mentorregistrations',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='멘토 이름'),
        ),
    ]
