# Generated by Django 4.2.6 on 2024-07-15 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_menteeapplications_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringdata',
            name='mentoring_id',
            field=models.ForeignKey(db_column='mentoring_id', on_delete=django.db.models.deletion.CASCADE, to='main.mentorregistrations'),
        ),
    ]
