# Generated by Django 4.2.6 on 2024-07-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_mentoringdata_mentoring_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorregistrations',
            name='status',
            field=models.CharField(choices=[('모집중', '모집중'), ('모집완료', '모집완료')], default='모집중', max_length=10, verbose_name='진행 상태'),
        ),
    ]
