# Generated by Django 4.2.6 on 2024-07-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_mentorregistrations_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringdata',
            name='status',
            field=models.CharField(choices=[('진행중', '진행중'), ('진행완료', '진행완료')], default='진행중', max_length=10, verbose_name='진행 상태'),
        ),
    ]
