# Generated by Django 4.2.6 on 2024-08-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='question_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
